### ISSUE TITLE
hi，预测函数predict_all_stock内发生错误。

### ISSUE THREAD

**Issue by c5433137** [tp-yan/WebStockPredict#9]
2020-07-25 16:34:01.389557: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-07-25 16:34:01.389754: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[Model] Loading model from file C:/Users/Administrator/python/WebStockPredict/LSTMPredictStock\saved_models\600718.h5
2020-07-25 16:34:03.076418: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2020-07-25 16:34:03.076598: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2020-07-25 16:34:03.080399: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: HR02019050061
2020-07-25 16:34:03.080638: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: HR02019050061
2020-07-25 16:34:03.081114: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-07-25 16:34:03.088054: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1ecfbf1c9b0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-25 16:34:03.088293: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "C:/Users/Administrator/python/WebStockPredict/LSTMPredictStock/run.py", line 259, in <module>
    predict_all_stock()
  File "C:/Users/Administrator/python/WebStockPredict/LSTMPredictStock/run.py", line 238, in predict_all_stock
    predict_list.append(prediction(stock_code=stock_code, real=True, pre_len=pre_len))
  File "C:/Users/Administrator/python/WebStockPredict/LSTMPredictStock/run.py", line 132, in prediction
    normalise=False
  File "C:\Users\Administrator\python\WebStockPredict\LSTMPredictStock\core\data_processor.py", line 36, in get_test_data
    x = data_windows[:, :-1]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

**Comment by c5433137** [comment]
已解决 是爬虫数据个数的问题
